# Generated by Django 3.2.2 on 2021-05-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_tone', '0005_alter_skintone_formfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Skintone',
        ),
    ]
